---
title: "Case Study 09"
author: Willow Flood
date: November 1, 2022
output: github_document
---
The libraries used in this case study
```{r message = FALSE}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
```
The data used in this case study
```{r}
data(world) 
data(us_states) 
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir) 
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```
Filtering the data so that it only contains from 1950 to present
```{r}
stormData = storm_data %>%
  filter(SEASON > 1949) %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))
```
Creating a bounding box of the data
```{r}
region = st_bbox(stormData)
```
Making the plot faceted by decade
```{r}
storm_map = ggplot(world) +
  geom_sf() +
  facet_wrap(~decade) +
  stat_bin2d(data=stormData, 
             aes(y=st_coordinates(stormData)[,2], 
                 x=st_coordinates(stormData)[,1]),bins=100) +
  scale_fill_distiller(palette="YlOrRd", 
                       trans="log", 
                       direction=-1, 
                       breaks = c(1,10,100,1000)) +
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) 
storm_map
```
Calculating the five states that have the most storms
```{r}
states = st_transform(us_states, crs = st_crs(stormData)) 
colnames(states)[2] = "state" 
storm_states <- st_join(stormData, states, join = st_intersects,left = F)
storms_top5 = storm_states %>%
  group_by(state) %>%
  summarise(storms=length(unique(NAME))) %>%
  arrange(desc(storms)) %>%
  st_set_geometry(NULL) %>%
  slice(1:5)
storms_top5
```