---
title: "Case Study 11"
author: Willow Flood
date: November 15, 2022
output: github_document
---
Libraries for this case study.
```{r message=FALSE warning=FALSE}
library(tidyverse)
library(spData)
library(sf)
library(mapview)
library(foreach)
library(doParallel)
library(tidycensus)
```
Setting up the data.
```{r}
getDoParWorkers() #Check registered cores
#registerDoParallel() This is the function to run if you have more than 1 core to do parallel processing on

# go to  http://api.census.gov/data/key_signup.html and get a key, then run the line below with your key.  Key is not pushed to GitHub.
census_api_key("26ab8d18f86e048d544c4fcffce3d5a20be623cf", install = TRUE)
```

```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T) 
```
Cropping the are for easier computation.
```{r}
e = c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
buffalo = st_crop(erie, e)
```
Writing a forloop to create one sf object.
```{r}
buf_block = foreach(i = unique(buffalo$variable), .combine = rbind) %do% {
  filter(buffalo,variable==i) %>%
    st_sample(size=.$value) %>%
    st_as_sf() %>%
    mutate(variable = i)
}
```
Creating a map of the data.
```{r}
mapview(buf_block, zcol = "variable", cex = 0.1, alpha = 0)
```
